spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/claims_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        "format_sql": true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: claim-system

server:
  port: 8080